GENPAT /R .\old\RESOURCE.AUD .\new\RESOURCE.SFX .\patch\RESOURCE.AUD.PAT
GENPAT /R .\old\RESOURCE.000 .\new\RESOURCE.000 .\patch\RESOURCE.000.PAT
GENPAT /R .\old\RESOURCE.MAP .\new\RESOURCE.MAP .\patch\RESOURCE.MAP.PAT
GENPAT /R .\old\SIERRA.EXE .\new\SIERRA.EXE .\patch\SIERRA.EXE.PAT
GENPAT /R .\old\INTERP.ERR .\new\INTERP.ERR .\patch\INTERP.ERR.PAT
GENPAT /R .\old\AUDBLAST.DRV .\new\AUDBLAST.DRV .\patch\AUDBLAST.DRV.PAT

pause